# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

foo7v2C <- function(dw, swapG) {
    .Call('_crspack_foo7v2C', PACKAGE = 'crspack', dw, swapG)
}

goo2C <- function(dw, dw1, m) {
    .Call('_crspack_goo2C', PACKAGE = 'crspack', dw, dw1, m)
}

DDstatV2C <- function(dw, iICGs = TRUE, get_var = TRUE) {
    .Call('_crspack_DDstatV2C', PACKAGE = 'crspack', dw, iICGs, get_var)
}

DDstatV1C <- function(dw) {
    .Call('_crspack_DDstatV1C', PACKAGE = 'crspack', dw)
}

var_funC <- function(dw) {
    .Call('_crspack_var_funC', PACKAGE = 'crspack', dw)
}

ASDstatV1C <- function(dw) {
    .Call('_crspack_ASDstatV1C', PACKAGE = 'crspack', dw)
}

ASDstatV2C <- function(dw, iICGs) {
    .Call('_crspack_ASDstatV2C', PACKAGE = 'crspack', dw, iICGs)
}

ASDstatV3C <- function(dw, Zvals, swapG, iICGs) {
    .Call('_crspack_ASDstatV3C', PACKAGE = 'crspack', dw, Zvals, swapG, iICGs)
}

ASDpvC <- function(dw, K) {
    .Call('_crspack_ASDpvC', PACKAGE = 'crspack', dw, K)
}

ASDpv3C <- function(dw, K, Zvals, swapG, iICGs) {
    .Call('_crspack_ASDpv3C', PACKAGE = 'crspack', dw, K, Zvals, swapG, iICGs)
}

